name: Release Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]*'
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 10.0.x

    - name: Update package version
      run: |
        $version = "${{github.ref_name}}"
        $packageJsonPath = "src/uMux/Client/public/umbraco-package.json"
        $packageJson = Get-Content $packageJsonPath | ConvertFrom-Json
        $packageJson.version = $version
        $packageJson.extensions[0].js += "?v=$version"
        $packageJson | ConvertTo-Json | Set-Content $packageJsonPath

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install npm dependencies
      run: npm install
      working-directory: src/uMux/Client

    - name: Build npm package
      run: npm run build
      working-directory: src/uMux/Client

    - name: Build & Pack
      run: dotnet pack src\uMux\uMux.csproj -c Release /p:Version=${{github.ref_name}}

    - name: Push to NuGet
      run: dotnet nuget push **\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json